# Generated by Django 3.2.6 on 2021-08-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0002_add_index_on_version_for_content_type_and_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='existing_versions',
            field=models.ManyToManyField(blank=True,
                                         related_name='revision_multiple',
                                                         help_text='Previous versions that have not been changed since the last revision',
                                                         verbose_name='existing_versions', to='reversion.Version')
        )
    ]
